"""is_active change to bool

Revision ID: 96e0da6ebb25
Revises: f941995c6ac3
Create Date: 2025-02-28 16:40:13.003170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e0da6ebb25'
down_revision: Union[str, None] = 'f941995c6ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        'users', 'is_active',
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        postgresql_using="is_active::boolean",
        existing_nullable=True
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
